### ISSUE TITLE
Add README event listening example

### ISSUE THREAD

**Issue by bryanhitc** [BryanHitchcock/lcu-sharp#11]
**Is your feature request related to a problem? Please describe.**
Currently, the README doesn't demonstrate how to listen to web socket events triggered by the league client.

**Describe the solution you'd like**
Outline a clear example of how to use the `ILeagueEventHandler`.

**Comment by ghost** [comment]
I think that the game flow event would be a good example of WebSocket event listening since the data returned is simple enough to understand. Unless having an event that returns JSON data would be more realistic (Such as /lol-champ-select/v1/session).
```
//Subscribe to the "gameflow-phase" to receive notifications about the client's state
api.EventHandler.Subscribe("/lol-gameflow/v1/gameflow-phase", ShowGameFlow) 

//Show what state the client is in
public void ShowGameFlow(object sender, LeagueEvent event){
	//Data returned from the client is a string containing the state of the client
	switch(e.Data.ToString()){
		case "None":
			Console.WriteLine("I'm in the main menu");
		case "ChampSelect":
			Console.WriteLine("I'm in Champion Select");
		case "Lobby":
			Console.WriteLine("I'm in a Lobby");
		case "InProgress":
			Console.WriteLine("I'm in a match");
	}
}
```

**Comment by bryanhitc** [comment]
Great idea! I'll incorporate this in the README and potentially add a more complex example later.
