### ISSUE TITLE
It needs System.Runtime 5.0.0.0

### ISSUE THREAD

**Issue by BULL3TB0T** [BryanHitchcock/lcu-sharp#19]
I can't add the LeagueApi to the Project. This is the error CS1705	`Assembly 'LCUSharp' with identity 'LCUSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
`

I tried installing the latest runtime but didn't work.

**Comment by bryanhitc** [comment]
This library now targets .NET 5.0, meaning you must use a runtime compatible with it. Please see #16 and its associated PR for context. Let me know if you have any additional questions.
