### ISSUE TITLE
Event problem

### ISSUE THREAD

**Issue by LiinxTV** [BryanHitchcock/lcu-sharp#21]
`public event EventHandler<LeagueEvent> GameFlowChanged;
private readonly TaskCompletionSource<bool> _work = new TaskCompletionSource<bool>(false);

public async Task EventExampleAsync()
{
    // Initialize a connection to the league client.
    var api = await LeagueClientApi.ConnectAsync();
    Console.WriteLine("Connected!");

    // Register game flow event.
    GameFlowChanged += OnGameFlowChanged;
    api.EventHandler.Subscribe("/lol-gameflow/v1/gameflow-phase", GameFlowChanged);

    // Wait until work is complete.
    await _work.Task;
    Console.WriteLine("Done.");
}

private void OnGameFlowChanged(object sender, LeagueEvent e)
{
    var result = e.Data.ToString();
    var state = string.Empty;

    switch (result)
    {
        case "None":
            state = "main menu";
            break;
        case "Lobby":
            state = "lobby";
            break;
        case "ChampSelect":
            state = "champ select";
            break;
        case "GameStart":
            state = "game started";
            break;
        case "InProgress":
            state = "game";
            break;
        case "WaitingForStats":
            state = "waiting for stats";
            break;
        default:
            state = $"unknown state: {result}";
            break;
    }

    // Print new state and set work to complete.
    Console.WriteLine($"Status update: Entered {state}.");
    _work.SetResult(true);
}`

I see Connected, but when i switch of game, it don't print anything

**Comment by bryanhitc** [comment]
Hi! I don't actively maintain this project, but I'm happy to try and help you with your problem.

Can you provide some steps that I can use to reproduce the issue + confirm that this is a bug? It still works for me:

![image](https://user-images.githubusercontent.com/11540371/146606339-f4c6dbdc-4504-4a80-a78d-b0c39423aebb.png)

Code gist link: https://gist.github.com/bryanhitc/31ab55cb808a8b7378c6bfda169e7fec
